import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

test('uses the Kath landing assets on the welcome screen', () => {
  const source = readFileSync(new URL('../src/main.jsx', import.meta.url), 'utf8');
  const styles = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
  const monogram = readFileSync(new URL('../src/assets/monogram.png', import.meta.url));
  const welcomeCard = source.match(/<div className="welcome-card">([\s\S]*?)<\/div>/)?.[1] || '';

  assert.equal(existsSync(new URL('../src/assets/landing-page.jpg', import.meta.url)), true);
  assert.equal(existsSync(new URL('../src/assets/first-page.jpg', import.meta.url)), true);
  assert.equal(existsSync(new URL('../src/assets/monogram.png', import.meta.url)), true);
  assert.equal(monogram[25], 6);
  assert.match(source, /import monogramImage from ['"]\.\/assets\/monogram\.png['"]/);
  assert.match(source, /className="welcome-monogram"/);
  assert.match(welcomeCard, /className="welcome-monogram"/);
  assert.match(source, /alt="Kathreen and Lawrence monogram"/);
  assert.match(source, /className={`welcome-envelope \$\{opening \? 'is-opening' : ''\}`}/);
  assert.match(source, /className="envelope-flap"/);
  assert.match(source, /disabled=\{opening\}/);
  assert.match(source, /startInvitationMusic\(musicRef\.current\)/);
  assert.match(source, /setOpened\(true\), reduce \? 0 : ENVELOPE_OPEN_DURATION/);
  assert.doesNotMatch(welcomeCard, /The wedding of/);
  assert.match(source, /In his light, we found each other\./);
  assert.match(source, /className="date-heading"/);
  assert.match(source, /className="date-subtitle"/);
  assert.match(source, /formatDateOnly\(liveEvent\.couple\.date\)/);
  assert.match(source, /formatTimeOfDay\(liveEvent\.couple\.date\)/);
  assert.match(source, /The details/);
  assert.match(source, /className="venue-schedule"/);
  assert.match(source, /className="venue-note"/);
  assert.match(source, /className="venue-qr"/);
  assert.match(source, /parents: \{ bride:/);
  assert.match(source, /function Entourage\(\{ event \}\)/);
  assert.match(source, /className="parents-grid"/);
  assert.match(source, /className="secondary-row"/);
  assert.match(source, /className="entourage-footer-grid"/);
  assert.match(source, /className="site-nav-monogram"/);
  assert.doesNotMatch(source, /className="hero-monogram"/);
  assert.match(source, /className="hero-event-meta"/);
  assert.match(source, /className="hero-venue"/);
  assert.match(source, /className="footer-monogram"/);
  assert.match(styles, /url\(['"]\.\/assets\/landing-page\.jpg['"]\)/);
  assert.match(styles, /url\(['"]\.\/assets\/first-page\.jpg['"]\)/);
  assert.match(styles, /\.hero::before \{[^}]*backdrop-filter: blur/);
  assert.match(styles, /\.hero \{[^}]*place-items: center/);
  assert.match(styles, /font-family: 'Bookman Old Style', 'Bookman', Georgia, serif/);
  assert.match(styles, /\.hero-event-meta \{[^}]*font-size: 1rem/);
  assert.match(styles, /\.hero-venue \{[^}]*font-size: 1\.45rem/);
  assert.match(styles, /\.hero-copy > p:not\(\.hero-venue\) \{[^}]*font-size: 1\.5rem/);
  assert.match(styles, /\.site-nav nav \{[^}]*font-size: \.82rem/);
  assert.match(styles, /\.footer-monogram \{[^}]*width: 82px/);
  assert.match(styles, /\.intro-section \{[^}]*background: var\(--white\)/);
  assert.match(styles, /\.date-heading \{[^}]*font-size: clamp\(3\.2rem, 6vw, 5\.7rem\)/);
  assert.match(styles, /\.countdown \{[^}]*grid-template-columns: repeat\(4/);
  assert.match(styles, /\.countdown-item \{[^}]*border: 1px solid #dfd5ca/);
  assert.match(styles, /\.details-section \{[^}]*background: var\(--white\)/);
  assert.match(styles, /\.venue-card \{[^}]*min-height: 520px/);
  assert.match(styles, /\.venue-qr \{[^}]*background: #f5eee6/);
  assert.match(styles, /\.parents-grid, \.honor-grid \{[^}]*grid-template-columns: repeat\(2/);
  assert.match(styles, /\.secondary-row \{[^}]*grid-template-columns: 220px 1fr/);
  assert.match(styles, /\.entourage-footer-grid \{[^}]*grid-template-columns: repeat\(4/);
  assert.match(styles, /landing-page\.jpg['"]\) 0% 16% \/ 130% auto no-repeat/);
  assert.match(styles, /width: min\(300px, calc\(100% - 32px\)\)/);
  assert.match(styles, /\.welcome-monogram \{ position: relative;[^}]*width: min\(130px, 100%\)/);
  assert.match(styles, /min-height: 310px/);
  assert.match(styles, /\.welcome-envelope\.is-opening \.envelope-flap/);
  assert.match(styles, /\.welcome-envelope\.is-opening \.welcome-card/);
  assert.match(styles, /\.envelope-flap \{ position: absolute; z-index: 2;/);
  assert.match(styles, /\.welcome-envelope-body \{[^}]*background: rgba\(245, 236, 228, \.78\)/);
  assert.match(styles, /\.envelope-flap \{[^}]*background: rgba\(248, 240, 233, \.7\)/);
});
